#!/bin/bash

export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

modprobe i2c-dev

npm start -- --start

./usr/src/app/ardupilot/build/pxfmini/bin/arducopter-quad -B udp:11.0.0.2:6000